label: Layouts
type: layout
layouts:
  - "1/1"
  - "1/2, 1/2"
  - "1/3, 1/3, 1/3"
  - "1/3, 2/3"
  - "2/3, 1/3"
  - "1/4, 1/4, 1/4, 1/4"
  - "1/4, 1/2, 1/4"
  - "1/4, 3/4"
  - "3/4, 1/4"
selector:
  size: large
fieldsets:
  default:
    label:
      en: Default
      de: Standard
    type: group
    fieldsets:
      - text
      - heading
      - layoutImage
      - coverImage
      - layoutQuote
  special:
    label:
      en: Special
      de: Speziell
    type: group
    fieldsets:
      - contact
      - infobox
      - links
      - special
      - card
  complex:
    label:
        en: Complex
        de: Komplex
    type: group
    fieldsets:
      - cta
      - addresses
      - testimonial
settings:
  fields:
    class:
      label: Background
      type: select
      width: 1/3
      options:
        none: None
        bg-layout-light: Light
        bg-layout-dark: Dark
    id:
      type: text
      width: 1/2
      help: Ignored right now
    image:
      label: Background image
      type: files
      help: Ignored right now
pretty: true
